version: '3.2'
services:

  morph-xr2rml:
    image: frmichel/morph-xr2rml:v1.3.2
    container_name: morph-xr2rml
    networks:
      - xr2rml-net
    volumes:
      - "./xr2rml_config:/xr2rml_config"
      - "./xr2rml_output:/xr2rml_output"
      - "./log:/log"

  mongo-xr2rml:
    image: mongo:4.4.6
    container_name: mongo-xr2rml    
    networks:
      - xr2rml-net
    volumes:
      - "./mongo_db:/data/db"
      - "./mongo_tools:/mongo_tools"
      - "./mongo_import:/mongo_import"

networks:
  xr2rml-net:
    driver: bridge

